In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

# creating arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)  # convert list to array
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(my_list)

list

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.arange(3.0)

array([0., 1., 2.])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(20,10)  # 1st arg >2nd arg but always first arg should be less than second arg

array([], dtype=int32)

In [15]:
np.arange(16,20)

array([16, 17, 18, 19])

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [18]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [19]:
ar = np.arange(-30,20)

In [20]:
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [21]:
np.arange(10,10)

array([], dtype=int32)

In [22]:
np.arange()

TypeError: arange() requires stop to be specified.

In [23]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [25]:
np.arange(10,30,40,35) # not accepted more than 3 arg

TypeError: Cannot interpret '35' as a data type

In [26]:
np.zeros(6) # parameter tuning

array([0., 0., 0., 0., 0., 0.])

In [27]:
zero = np.zeros([2,2])
print(zero)

[[0. 0.]
 [0. 0.]]


In [28]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
n=(6,7)
n1=(6,8)
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [30]:
n=(6,7)
n1=(6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
np.ones(3)

array([1., 1., 1.])

In [32]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [33]:
np.ones(4)


array([1., 1., 1., 1.])

In [34]:
np.ones(n)  # the output we got is float

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [35]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns  byusing dtype=int
# we are converting above float values to int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
np.twos((2,4))  

AttributeError: module 'numpy' has no attribute 'twos'

In [37]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [38]:
range(5)

range(0, 5)

In [39]:
r = range(5)
r

range(0, 5)

In [40]:
for i in r:
    print(i)

0
1
2
3
4


In [41]:
list(range(5))

[0, 1, 2, 3, 4]

In [42]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [44]:
np.random.rand(5)  # 5 random numbers generated

array([0.31865216, 0.59594978, 0.20874333, 0.87763748, 0.47083197])

In [45]:
np.rand(4) # module is missing which is random

AttributeError: module 'numpy' has no attribute 'rand'

In [46]:
np.random.rand(2,4)

array([[0.86913003, 0.1575282 , 0.29219025, 0.23216337],
       [0.21948316, 0.49784648, 0.01166971, 0.859419  ]])

In [47]:
np.random.randint(2,4)


3

In [48]:
np.random.randint(2,20) # 20 will be exclusive

9

In [49]:
np.random.randint(0,1)

0

In [50]:
np.random.randint(10,20,3)   # 3 random numbers will be generated bw range 10 t0 20  where 20 will be exclusive

array([18, 19, 18])

In [51]:
np.random.randint(1,6,4)

array([3, 5, 1, 4])

In [52]:
np.random.randint(10,40,(10,10))  # generate the elements bw 10 to 39 coz 40 is exclusive with 10 rows and 10 clms

array([[28, 36, 16, 20, 36, 24, 35, 28, 25, 22],
       [27, 39, 12, 33, 22, 35, 33, 16, 36, 19],
       [27, 23, 18, 14, 28, 37, 36, 35, 38, 39],
       [24, 22, 12, 29, 20, 22, 25, 35, 17, 30],
       [34, 11, 29, 38, 13, 15, 28, 17, 19, 22],
       [23, 14, 34, 10, 30, 28, 24, 14, 20, 25],
       [18, 25, 18, 37, 29, 28, 17, 34, 31, 24],
       [10, 36, 15, 16, 19, 19, 12, 10, 13, 30],
       [26, 26, 30, 24, 19, 15, 28, 32, 26, 14],
       [37, 13, 20, 31, 16, 12, 39, 28, 25, 26]])

In [53]:
b=np.random.randint(10,20,(5,10))
b                    

array([[15, 17, 19, 10, 14, 12, 13, 16, 12, 14],
       [15, 18, 16, 17, 12, 18, 17, 19, 16, 14],
       [18, 12, 19, 17, 16, 12, 12, 18, 16, 14],
       [13, 13, 17, 13, 19, 16, 12, 10, 16, 18],
       [16, 17, 17, 14, 10, 10, 14, 15, 10, 13]])

In [54]:
b=np.random.randint(10,20,(5,4))
b 

array([[11, 12, 19, 19],
       [16, 13, 15, 19],
       [15, 14, 16, 13],
       [14, 11, 18, 15],
       [13, 12, 12, 11]])

In [55]:
b[:]

array([[11, 12, 19, 19],
       [16, 13, 15, 19],
       [15, 14, 16, 13],
       [14, 11, 18, 15],
       [13, 12, 12, 11]])

In [56]:
b[0:2]

array([[11, 12, 19, 19],
       [16, 13, 15, 19]])

In [57]:
b

array([[11, 12, 19, 19],
       [16, 13, 15, 19],
       [15, 14, 16, 13],
       [14, 11, 18, 15],
       [13, 12, 12, 11]])

In [58]:
b[0:-1]

array([[11, 12, 19, 19],
       [16, 13, 15, 19],
       [15, 14, 16, 13],
       [14, 11, 18, 15]])

In [59]:
b[0:-2]

array([[11, 12, 19, 19],
       [16, 13, 15, 19],
       [15, 14, 16, 13]])

In [60]:
b[0:-4]

array([[11, 12, 19, 19]])

In [61]:
b

array([[11, 12, 19, 19],
       [16, 13, 15, 19],
       [15, 14, 16, 13],
       [14, 11, 18, 15],
       [13, 12, 12, 11]])

In [62]:
b[0,2]

19

In [63]:
b[1,3]   # there is difference between : & , need to identify

19

In [64]:
np.random.randint(10,20,(4,4))

array([[10, 10, 10, 14],
       [14, 16, 10, 13],
       [14, 15, 19, 16],
       [18, 18, 13, 11]])

In [65]:
  #  if we do np. tab we can see all functions of numpy

# operations

In [66]:
# how a image is convert to  matrix

In [67]:
a = np.random.randint(10,20,5)
a

array([19, 17, 19, 16, 11])

In [68]:
arr

array([0, 1, 2, 3, 4, 5])

In [74]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[71, 19,  1, 65, 14, 26, 26, 10, 22, 84],
       [52, 87, 69, 43, 85, 28, 66, 74, 38, 52],
       [36, 48, 81, 19, 68, 95, 11, 23, 48, 31],
       [38,  3, 41, 93, 23, 60, 69, 22, 77, 55],
       [57, 95, 92, 73, 28, 80, 31, 21, 94, 83],
       [37, 51, 46, 61, 77, 63, 22, 77, 14, 88],
       [70, 26,  7, 84, 62, 36, 21, 92, 58, 53],
       [43, 98, 12, 54, 73, 86, 87, 84, 97,  8],
       [51, 33, 33, 97, 42, 93, 96, 60, 97, 60],
       [64, 37,  4, 91, 44, 73,  9, 78, 28, 64]])

In [75]:
arr

array([0, 1, 2, 3, 4, 5])

In [76]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [77]:
arr[:4]

array([0, 1, 2, 3])

In [78]:
arr2


array([[71, 19,  1, 65, 14, 26, 26, 10, 22, 84],
       [52, 87, 69, 43, 85, 28, 66, 74, 38, 52],
       [36, 48, 81, 19, 68, 95, 11, 23, 48, 31],
       [38,  3, 41, 93, 23, 60, 69, 22, 77, 55],
       [57, 95, 92, 73, 28, 80, 31, 21, 94, 83],
       [37, 51, 46, 61, 77, 63, 22, 77, 14, 88],
       [70, 26,  7, 84, 62, 36, 21, 92, 58, 53],
       [43, 98, 12, 54, 73, 86, 87, 84, 97,  8],
       [51, 33, 33, 97, 42, 93, 96, 60, 97, 60],
       [64, 37,  4, 91, 44, 73,  9, 78, 28, 64]])

In [79]:
arr2[0:5]

array([[71, 19,  1, 65, 14, 26, 26, 10, 22, 84],
       [52, 87, 69, 43, 85, 28, 66, 74, 38, 52],
       [36, 48, 81, 19, 68, 95, 11, 23, 48, 31],
       [38,  3, 41, 93, 23, 60, 69, 22, 77, 55],
       [57, 95, 92, 73, 28, 80, 31, 21, 94, 83]])

In [80]:
arr2

array([[71, 19,  1, 65, 14, 26, 26, 10, 22, 84],
       [52, 87, 69, 43, 85, 28, 66, 74, 38, 52],
       [36, 48, 81, 19, 68, 95, 11, 23, 48, 31],
       [38,  3, 41, 93, 23, 60, 69, 22, 77, 55],
       [57, 95, 92, 73, 28, 80, 31, 21, 94, 83],
       [37, 51, 46, 61, 77, 63, 22, 77, 14, 88],
       [70, 26,  7, 84, 62, 36, 21, 92, 58, 53],
       [43, 98, 12, 54, 73, 86, 87, 84, 97,  8],
       [51, 33, 33, 97, 42, 93, 96, 60, 97, 60],
       [64, 37,  4, 91, 44, 73,  9, 78, 28, 64]])

In [81]:
arr2[1,5]

28

In [82]:
arr2[-5,5]

63

In [83]:
arr2[-5,-5]

63

In [84]:
arr2

array([[71, 19,  1, 65, 14, 26, 26, 10, 22, 84],
       [52, 87, 69, 43, 85, 28, 66, 74, 38, 52],
       [36, 48, 81, 19, 68, 95, 11, 23, 48, 31],
       [38,  3, 41, 93, 23, 60, 69, 22, 77, 55],
       [57, 95, 92, 73, 28, 80, 31, 21, 94, 83],
       [37, 51, 46, 61, 77, 63, 22, 77, 14, 88],
       [70, 26,  7, 84, 62, 36, 21, 92, 58, 53],
       [43, 98, 12, 54, 73, 86, 87, 84, 97,  8],
       [51, 33, 33, 97, 42, 93, 96, 60, 97, 60],
       [64, 37,  4, 91, 44, 73,  9, 78, 28, 64]])

In [85]:
arr2[-1,-2]

28

In [86]:
arr2[::-1]

array([[64, 37,  4, 91, 44, 73,  9, 78, 28, 64],
       [51, 33, 33, 97, 42, 93, 96, 60, 97, 60],
       [43, 98, 12, 54, 73, 86, 87, 84, 97,  8],
       [70, 26,  7, 84, 62, 36, 21, 92, 58, 53],
       [37, 51, 46, 61, 77, 63, 22, 77, 14, 88],
       [57, 95, 92, 73, 28, 80, 31, 21, 94, 83],
       [38,  3, 41, 93, 23, 60, 69, 22, 77, 55],
       [36, 48, 81, 19, 68, 95, 11, 23, 48, 31],
       [52, 87, 69, 43, 85, 28, 66, 74, 38, 52],
       [71, 19,  1, 65, 14, 26, 26, 10, 22, 84]])

In [87]:
arr2

array([[71, 19,  1, 65, 14, 26, 26, 10, 22, 84],
       [52, 87, 69, 43, 85, 28, 66, 74, 38, 52],
       [36, 48, 81, 19, 68, 95, 11, 23, 48, 31],
       [38,  3, 41, 93, 23, 60, 69, 22, 77, 55],
       [57, 95, 92, 73, 28, 80, 31, 21, 94, 83],
       [37, 51, 46, 61, 77, 63, 22, 77, 14, 88],
       [70, 26,  7, 84, 62, 36, 21, 92, 58, 53],
       [43, 98, 12, 54, 73, 86, 87, 84, 97,  8],
       [51, 33, 33, 97, 42, 93, 96, 60, 97, 60],
       [64, 37,  4, 91, 44, 73,  9, 78, 28, 64]])

In [88]:
arr2[::-2]

array([[64, 37,  4, 91, 44, 73,  9, 78, 28, 64],
       [43, 98, 12, 54, 73, 86, 87, 84, 97,  8],
       [37, 51, 46, 61, 77, 63, 22, 77, 14, 88],
       [38,  3, 41, 93, 23, 60, 69, 22, 77, 55],
       [52, 87, 69, 43, 85, 28, 66, 74, 38, 52]])

In [89]:
arr2[::-3]

array([[64, 37,  4, 91, 44, 73,  9, 78, 28, 64],
       [70, 26,  7, 84, 62, 36, 21, 92, 58, 53],
       [38,  3, 41, 93, 23, 60, 69, 22, 77, 55],
       [71, 19,  1, 65, 14, 26, 26, 10, 22, 84]])

In [90]:
arr

array([0, 1, 2, 3, 4, 5])

In [91]:
arr.max()

5

In [92]:
arr.min()

0

In [93]:
arr.mean()

2.5

In [94]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [97]:
from numpy import *
a=array([1,2,3,4,9])
median(a)

3.0

In [98]:
arr


array([0, 1, 2, 3, 4, 5])

In [99]:
arr.reshape(3,2)  # RESHAPE HAS 3 TYPE OF ORDERS C,A,F

array([[0, 1],
       [2, 3],
       [4, 5]])

In [100]:
arr.reshape(4,1)

ValueError: cannot reshape array of size 6 into shape (4,1)

In [101]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [102]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
arr.reshape(4,1)

ValueError: cannot reshape array of size 6 into shape (4,1)

In [104]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [105]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [106]:
arr.reshape(1,5)

ValueError: cannot reshape array of size 6 into shape (1,5)

In [107]:
arr

array([0, 1, 2, 3, 4, 5])

In [108]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [109]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [110]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [111]:
arr.reshape(2,3,order='k')

ValueError: order 'K' is not permitted for reshaping

In [112]:
arr

array([0, 1, 2, 3, 4, 5])

In [113]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [114]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [115]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [116]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [117]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [118]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [119]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [120]:
arr

array([0, 1, 2, 3, 4, 5])

# INDEXING

In [122]:
mat = np.arange(0,100).reshape(10,10)

In [123]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [124]:
row = 4
col = 5


In [125]:
row

4

In [126]:
col

5

In [127]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [128]:
mat[row,col]  # by default it takes above row , col values as 4 ,5 

45

In [129]:
mat[4,5]

45

In [130]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [131]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [132]:
col = 6

In [133]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [134]:
# with slices
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [135]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [137]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [138]:
row

4

In [139]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [140]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [141]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [142]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [143]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [144]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [145]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [146]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [147]:
row

4

In [148]:
col

6

In [149]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [150]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [152]:
mat[1,4]

14

In [153]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [154]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [155]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [157]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [158]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [159]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [160]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [162]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [163]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [164]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [165]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [166]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [167]:
mat[::-4]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [168]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [169]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [171]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [172]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [173]:
mat[0,1]

1

In [174]:
mat[1,6]

16

In [175]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [176]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [177]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [178]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [179]:
mat[0:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [182]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [180]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [181]:
mat[3,5]

35

In [183]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
mat[1:2,2:4]

array([[12, 13]])

In [185]:
mat[2:3,2:3]

array([[22]])

In [186]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
mat[2:3,4:5]

array([[24]])

#  MASKING

In [189]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [190]:
id(mat)

1852997266928

In [191]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [193]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [194]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [195]:
mat[mat==50]

array([50])

In [196]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [197]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [199]:
a3 = mat[mat>=50] 
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [200]:
a4 = mat[mat==50] 
a4

array([50])

In [201]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [203]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])